dist: xenial
sudo: required
language: python
cache: pip
python:
- 3.7
env:
  global:
  - secure: kDAI818hwV0MF87EI0PANbIsX/AIiNrsI0+hdiOd4bmH7VGM71/qjaaoZVyDmfkkEvA/qrn4LUuH3YQ7VTtrgZm/ggDLxi03XIvJwez9knSc9x/XLdd/Xj/Q36KYrccuZwJsDUAtjiL6oWp84wbuvESeuFdp9ufn5mSMRAcaQbIdYudxGbU7AQrP0CC5huJvF8aoaIZFwhV2d+n9YLqxpZ9Etax5BV+cWAu9AXGu+gt4xF1dKcYxqsdSvUahrq8Z2IbCcy/KSBbZLjmwP8ze4nFl0yocW++sNqr0oEa0KNBEgwO6vvolmkPm93dz7AewMxkWSeDFCSZKHmZWuqVVllUuJfKOUOeF18NjYSKUayuHzml7CBQZgMBjPYdaa8jIgp/uHwMwPYYP/a6zSkevZ0Dqkq/qREF3NCVXs8BLgM8c9XcI1r6D9U80sMVj4829/tEikK9QqO6W0Q7qf0+V9j48PR5qZXbIthj+pon7Q6k3dNUvaAKWOalOT5IS5bBp9gLrGDakhnB+iRTZ8MnFXMT59XI9pvTsoFYxBsWcY0zTaxiivKJ25eCeESNVnqBWR01/TotsdeIcyF9dbsAT/hmp8hMtmi009eIPdVkyMoKHQXEYN3z4B7Ux11clVLDIsY9BX91XVaagXKEUppaIadlEnRb5heZRzXBENgRa/XI=
before_install:
- tests/__isfork.sh || travis_terminate 0
- openssl aes-256-cbc -K $encrypted_45757fbb12c0_key -iv $encrypted_45757fbb12c0_iv
  -in id_rsa.travis.enc -out id_rsa.travis -d
- sudo apt-get -y install build-essential python-dev libffi-dev libssl-dev
install:
- tests/__isfork.sh || travis_terminate 0
- export PATH=$HOME/.local/bin:$PATH
- pip install pip setuptools --upgrade
- $(which pip) install virtualenv
- $(which virtualenv) venv
- source venv/bin/activate
- $(which pip) install -r tests/requirements.txt
before_script:
- tests/__isfork.sh || travis_terminate 0
- chmod 600 id_rsa.travis && chmod 644 id_rsa.travis.pub
- export NAME=$(uuidgen)
- export RESOLVER=$(grep nameserver /etc/resolv.conf)
- $(which python) tests/testbuild.py digitalocean --create --name ${NAME} --api_token=$do_api_v2_token
  --branch=$TRAVIS_BRANCH --region=$do_region || ($(which python) tests/testbuild.py digitalocean
  --destroy --name ${NAME} --api_token=$do_api_v2_token && false)
script:
- tests/__isfork.sh || travis_terminate 0
- true
after_script:
- tests/__isfork.sh || travis_terminate 0
- printf "${RESOLVER}\n" | sudo tee /etc/resolv.conf
- $(which python) tests/testbuild.py digitalocean --destroy --name ${NAME} --api_token=$do_api_v2_token
after_success:
- tests/__isfork.sh || travis_terminate 0
- true
notifications:
  slack:
    secure: onMIdghH50Z0UKQ3/zmQ4fNGtBnW8Mumkvq6CvoYuPB35UzrBd3bA0jVnmkyRFStb7Y19IV4ABx2/9f+zgtrXfV0wk2KgbNkg/NTbLZPZ4Y9gQK2cxrVYQLFQk/UNjT3SzReYnkK02CqBXZy2jVmOIk/EIPchb1FAk2fvC4mAlFdu4eziG6dqZgukcqwxVdZPqap12rIFxTPa489HHR6TRvWf/wdQtbh9CwQwXhhqZa8Dadytb9kr2UVh4wTZ83thohRyO/oLZjFhYFQ0Sxd1QXZs+1z70bUC3Q6cgsg3tW7KB9Z84EvvrQFv6Jp8bfzecWwqiGHLcVc6ZIfZueQM+ceWBKf/4QN7Nt+Njv/PZtNUuvKg4XTLfrvL0m39HAHYr5rnSvxY3+MByQ/e45VPBvXBr+hFiEpyAvNXgDVr17kC+FzzemHnzH24806eaOgouRkrYV+rXEoGfVQe1TGVdeHUeumLyis4YYmlf20pR8xhuhEr383+9q0fzCvqdqHhH/sC3F3xOCAvVHqdNGPm9zOpxDASLCyMf40NB1s+dEOzYfr1sKQFa1ZzkGqwKDI1myKoLppgMlEz8ewwZn6RIv+mh5WBobrBg5Ebu/U/iZn5S6qeighb9Ph0Fk57Dn/jJRm8utYhahmB0nfopFAiucUgl0btrmKuqCaagtS92Q=
